# Generated by Django 3.2.5 on 2023-03-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0003_auto_20230309_1709'),
        ('patient', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='age',
            field=models.IntegerField(default=0, verbose_name="Age in Month's"),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientQuestion', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questioncategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionCategory', to='questioncategory.questioncategory'),
        ),
    ]
