# Generated by Django 3.2.5 on 2023-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_questionanswer_visitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='tools',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tools'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='whattodo',
            field=models.CharField(default='What to do or watch', max_length=50, verbose_name='What to do or watch'),
        ),
    ]
