# Generated by Django 3.2.5 on 2023-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20230324_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.CharField(max_length=180, verbose_name='Question'),
        ),
    ]
