# Generated by Django 3.2.5 on 2023-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_questionnaire_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='tools',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tools'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='whattodo',
            field=models.CharField(default='What to do or watch', max_length=255, verbose_name='What to do or watch'),
        ),
    ]
