# Generated by Django 3.2.5 on 2023-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20230324_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='whattodo',
            field=models.CharField(blank=True, default='What to do or watch', max_length=255, null=True, verbose_name='What to do or watch'),
        ),
    ]
