# Generated by Django 3.2.5 on 2023-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioncategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='age',
            field=models.IntegerField(default=0, verbose_name="Age in Month's"),
        ),
    ]
