# Generated by Django 3.2.5 on 2023-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='Full name')),
                ('dateofbirth', models.DateField()),
                ('facility', models.CharField(max_length=180, verbose_name='Facility name')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Patient Infomartion',
                'verbose_name_plural': 'Patient Infomartions',
            },
        ),
    ]
