# Generated by Django 3.2.5 on 2023-03-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='123 mikocheni Dsm', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(default='0712xxxxxx', max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
