# Generated by Django 3.2.5 on 2023-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20230314_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='childAG',
            field=models.IntegerField(default=0, verbose_name='Age Grouo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parentfull_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Parent Full name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=180, verbose_name='Child Initals'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
